cglib/cglib

cglib/src/main/java/net/sf/cglib/beans/BeanCopier.java
cglib/src/test/java/net/sf/cglib/beans/SampleGetter.java
cglib/src/test/java/net/sf/cglib/beans/SampleSetter.java
cglib/src/test/java/net/sf/cglib/beans/TestBeanCopier.java

As reported in https://github.com/cglib/cglib/issues/29

Fixed bean copier that read getters instead of setters.

---

cglib/pom.xml
cglib/src/main/java/net/sf/cglib/core/ClassEmitter.java
cglib/src/main/java/net/sf/cglib/core/ClassNameReader.java
cglib/src/main/java/net/sf/cglib/core/CodeEmitter.java
cglib/src/main/java/net/sf/cglib/core/DebuggingClassWriter.java
cglib/src/main/java/net/sf/cglib/core/DefaultGeneratorStrategy.java
cglib/src/main/java/net/sf/cglib/core/LocalVariablesSorter.java
cglib/src/main/java/net/sf/cglib/proxy/BridgeMethodResolver.java
cglib/src/main/java/net/sf/cglib/transform/AbstractClassLoader.java
cglib/src/main/java/net/sf/cglib/transform/AbstractClassTransformer.java
cglib/src/main/java/net/sf/cglib/transform/AbstractTransformTask.java
cglib/src/main/java/net/sf/cglib/transform/AnnotationVisitorTee.java
cglib/src/main/java/net/sf/cglib/transform/ClassTransformer.java
cglib/src/main/java/net/sf/cglib/transform/ClassTransformerTee.java
cglib/src/main/java/net/sf/cglib/transform/ClassVisitorTee.java
cglib/src/main/java/net/sf/cglib/transform/FieldVisitorTee.java
cglib/src/main/java/net/sf/cglib/transform/MethodVisitorTee.java
cglib/src/main/java/net/sf/cglib/transform/impl/AddDelegateTransformer.java
cglib/src/test/java/net/sf/cglib/transform/DumpFieldsTask.java
pom.xml

By default this doesn't change anything, but it allows you to pass args to the build to change the language level of the test classes. For example to run the tests in Java 8 mode you would run
```
mvn clean test -Djava.test.version.source=1.8 -Djava.test.version.target=1.8
```
(this produces 5 test failures)
Or to see if the tests pass with the new Java 8 parameter name reflection flag you would run
```
mvn clean test -Djava.test.version.source=1.8 -Djava.test.version.target=1.8 -Djava.test.compiler.argument=-parameters
```
(this produces 15 test failures)
Related to issue #33, I was going to write a small Java 8 test but I figured it would be much more robust to run the entire test suite against Java 8. Unfortunately this type of testing would have to be manual, I could try making it …

Make test flags configurable

---

cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java

Polish exception message to avoid 'class class' like the following exception:
```
Caused by: java.lang.IllegalArgumentException: Cannot subclass final class class com.sun.proxy.$Proxy88
```

Polish exception message to avoid 'class class'.

---

cglib/src/main/java/net/sf/cglib/core/VisibilityPredicate.java
cglib/src/test/java/net/sf/cglib/reflect/TestFastClass.java

There were 2 issues here
VisibilityPredicate would assume that default acceess
(package-private) was always fine as long as the member in question
was in the same package as the generated type.  In fact it needs to
also be in the same classloader.  This is normally a non-issue since
cglib tries to generate types into the types classloader.  The main
time this doesn't work is for classes on the bootstrap classpath (jdk
types).  So this adds a specific workaround for that.
VisibilityPredicate also assumed that protected access restricted
visibility to subtypes only, this is too strict, protected members are
also visible to types in the same package.
This should ultimately allow guice to drop some !protected checks in a
few places.
A super corrected fix would have VisibilityPredicate take …

Fix a few issues in VisibilityPredicate that prevent FastClass from generating accessors for protected methods

---

cglib/src/main/java/net/sf/cglib/core/ClassesKey.java
cglib/src/main/java/net/sf/cglib/core/Constants.java
cglib/src/main/java/net/sf/cglib/core/Customizer.java
cglib/src/main/java/net/sf/cglib/core/DefaultNamingPolicy.java
cglib/src/main/java/net/sf/cglib/core/EmitUtils.java
cglib/src/main/java/net/sf/cglib/core/FieldTypeCustomizer.java
cglib/src/main/java/net/sf/cglib/core/KeyFactory.java
cglib/src/main/java/net/sf/cglib/core/KeyFactoryCustomizer.java
cglib/src/main/java/net/sf/cglib/core/WeakIdentityKey.java
cglib/src/main/java/net/sf/cglib/core/internal/CustomizerRegistry.java
cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java
cglib/src/test/java/net/sf/cglib/beans/TestBeanMap.java
cglib/src/test/java/net/sf/cglib/proxy/TestEnhancer.java
cglib/src/test/java/net/sf/cglib/proxy/TestMixin.java
pom.xml

Previously `KeyFactory` generated `java.lang.Class` fields even with `CLASS_BY_NAME` customization.
That might lead to unexpected class and classloader leak.
The fix ensures `KeyFactory` uses `java.lang.String` to store class names.
It should make no harm as CGLIB uses per-classloader cache, thus class name should be sufficiently unique.

Fix permgen leak by storing Class instances as String

---

cglib/src/main/java/net/sf/cglib/core/AbstractClassGenerator.java
cglib/src/main/java/net/sf/cglib/core/ClassesKey.java
cglib/src/main/java/net/sf/cglib/core/Constants.java
cglib/src/main/java/net/sf/cglib/core/Customizer.java
cglib/src/main/java/net/sf/cglib/core/DefaultNamingPolicy.java
cglib/src/main/java/net/sf/cglib/core/EmitUtils.java
cglib/src/main/java/net/sf/cglib/core/FieldTypeCustomizer.java
cglib/src/main/java/net/sf/cglib/core/HashCodeCustomizer.java
cglib/src/main/java/net/sf/cglib/core/KeyFactory.java
cglib/src/main/java/net/sf/cglib/core/KeyFactoryCustomizer.java
cglib/src/main/java/net/sf/cglib/core/ReflectUtils.java
cglib/src/main/java/net/sf/cglib/core/WeakIdentityKey.java
cglib/src/main/java/net/sf/cglib/core/internal/CustomizerRegistry.java
cglib/src/main/java/net/sf/cglib/core/internal/Function.java
cglib/src/main/java/net/sf/cglib/core/internal/LoadingCache.java
cglib/src/main/java/net/sf/cglib/proxy/CallbackInfo.java
cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java
cglib/src/test/java/net/sf/cglib/beans/TestBeanMap.java
cglib/src/test/java/net/sf/cglib/proxy/TestEnhancer.java
cglib/src/test/java/net/sf/cglib/proxy/TestMixin.java
cglib/src/test/java/net/sf/cglib/reflect/TestFastClass.java
pom.xml

This fix removes `synchronization` in case relevant class is already cached.
The change comes on top of "fix permgen" (it reuses `WeakIdentityKey`)
Measurements (java 1.8u60, i7-4960HQ CPU @ 2.60GHz):
Response time is 15 times better.
Heap allocation is 5 times less.
Before:
```
Benchmark                                       Mode  Cnt     Score     Error   Units
BeansBenchmark.newInstance                      avgt    5  2135,987 ± 262,118   ns/op
BeansBenchmark.newInstance:·gc.alloc.rate.norm  avgt    5  1240,021 ±   0,168    B/op
```
After:
```
Benchmark                                       Mode  Cnt     Score     Error   Units
BeansBenchmark.newInstance                      avgt    5   142,438 ±   8,209   ns/op
BeansBenchmark.newInstance:·gc.alloc.rate.norm  avgt    5   256,001 ± …
```

Concurrent cache of generated classes

---

cglib/src/main/java/net/sf/cglib/core/ReflectUtils.java
cglib/src/test/java/net/sf/cglib/proxy/TestEnhancer.java
cglib/src/test/java/net/sf/cglib/reflect/TestFastClass.java

For best performance, proxy objects should not override #finalize as it does not make sense anyway
Before:
```
Benchmark                                        Mode  Cnt     Score     Error   Units
BeansBenchmark.newInstance                       avgt    5  2390,777 ± 163,965   ns/op
BeansBenchmark.newInstance:·gc.alloc.rate.norm   avgt    5  1240,001 ±   0,001    B/op
```
After:
```
Benchmark                                        Mode  Cnt     Score     Error   Units
BeansBenchmark.newInstance                       avgt    5  1786,696 ± 137,659   ns/op
BeansBenchmark.newInstance:·gc.alloc.rate.norm   avgt    5  1200,001 ±   0,001    B/op
```

Skip finalize while building proxy as there is no sense in doing that

---

cglib/src/main/java/net/sf/cglib/core/AbstractClassGenerator.java
cglib/src/test/java/net/sf/cglib/proxy/TestEnhancer.java

1) Ensure that NamingPolicies that doesn't check the predicate still get their names reserved.
2) Fix the double-checked locking when looking up cached ClassLoaderData, otherwise we lose reserved names & generation data and lead to duplicating classes accidentally (if multiple threads try to create subclasses for a single classloader at the same time).

Fix regression & bugs

---

cglib/src/main/java/net/sf/cglib/core/AbstractClassGenerator.java
cglib/src/main/java/net/sf/cglib/proxy/CallbackFilter.java
cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java
cglib/src/test/java/net/sf/cglib/proxy/TestEnhancer.java

Enable reuse of generated by Enhancer classes across GC in case CallbackFilter might become unreachable
In case CallbackFilter becomes unreachable, EnhancerKey's WeakCacheKey<CallbackFilter> field became null,
thus it effectively rendered EnhancerKey to be useless, thus the generated class became inaccessible.
The fix is to add a strong reference from generated class to the CallbackFilter, so the key does not expire,
and the generated class can be reused.
closes #80

Enable reuse of generated by Enhancer classes across GC 

---

.travis.yml
pom.xml

I've marked jdk9 job as "allowed failure" since jdk9 tests still have failures even if using the latest ASM 6.0_ALPHA.
Differences of java 9 vs pre-java 9 build:
* source=target=1.6 (1.5 is not supported in java 9)
* ASM version == 6.0_ALPHA (for java 9 bytecode support)
There are two kind of failures:
```
testSql(net.sf.cglib.proxy.TestEnhancer)  Time elapsed: 0.001 sec  <<< ERROR!
net.sf.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@9-ea/BuiltinClassLoader.java:366)
at java.lang.ClassLoader.loadClass(java.base@9-ea/ClassLoader.java:419)
at java.lang.ClassLoader.defineClass1(java.base@9-ea/Native Method)
at java.lang.ClassLoader.defineClass(java.base@9-ea/ClassLoader.java:942)
at …
```

Add JDK9 Travis job

---

cglib/src/main/java/net/sf/cglib/core/ReflectUtils.java
cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java
cglib/src/test/java/net/sf/cglib/proxy/TestEnhancer.java

Here's alternative approach to class instantiation (this PR is alternative to #79).
Note: the same generated class might be used with different constructors later, thus there should be something like an inline cache (otherwise it will end up with some kind of search for the proper constructor).
Here I implement 1-entry inline cache (== remember just one constructor for the class, and use it).
If user uses more than one constructor per proxy, the code falls back to `ReflectionUtils.newInstance(...)`, and it will be rather slow: https://github.com/cglib/cglib/pull/82/files#diff-173a9c4b512f39086ed564b6320318e2R422
The results are as follows:
```
1.7u55, factory
Benchmark                                                    Mode  Cnt     Score    Error   Units
BeansBenchmark.newInstance …
```

Instantiate proxy classes via reflection, remove Enhancer.createFactory

---

cglib/src/main/java/net/sf/cglib/proxy/BridgeMethodResolver.java
cglib/src/main/java/net/sf/cglib/proxy/CallbackGenerator.java
cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java
cglib/src/main/java/net/sf/cglib/proxy/MethodInterceptorGenerator.java
cglib/src/main/java/net/sf/cglib/proxy/NoOpGenerator.java
cglib/src/test/java/net/sf/cglib/proxy/TestEnhancer.java

This fixes a TODO in Enhancer: the assumption that a bridge's parameters
are assignable to the target's parameters doesn't hold in certain
cross-compilation scenarios.
The included test case fails with a VerifyError if the checkcasts are
omitted.
Also, make BridgeMethodResolver use the same class loader as Enhancer to
make it easier to test.

Add checkcasts for arguments of invoked bridges

---

.travis.yml
pom.xml

maven central doesn't support java6 anymore after they updated their TLS requirements (https://blog.sonatype.com/enhancing-ssl-security-and-http/2-support-for-central).  java6 is old, we don't need to support it anymore.

remove java6 support from pom & travis

---

cglib/src/main/java/net/sf/cglib/core/AsmApi.java
cglib/src/main/java/net/sf/cglib/core/Constants.java
cglib/src/test/java/net/sf/cglib/core/AsmApiTest.java

Full support for Java 11 bytecode requires ASM7_EXPERIMENTAL. The
approach used here is similar to byte-buddy's:
https://github.com/raphw/byte-buddy/blob/30c31ab403eedce386e28acc3e6aee2a7e2e0752/byte-buddy-dep/src/main/java/net/bytebuddy/utility/OpenedClassReader.java#L42

Support ASM7_EXPERIMENTAL if system property is set

---

cglib/src/main/java/net/sf/cglib/core/AsmApi.java
cglib/src/test/java/net/sf/cglib/core/AsmApiTest.java
pom.xml

Also ignore system property for using
Opcodes.ASM7_EXPERIMENTAL (which no longer exists).

Update to ASM 7.0 and default to Opcodes.ASM7

---

cglib/src/main/java/net/sf/cglib/beans/BulkBeanEmitter.java

Array lengths are always >= 0, this code was trying to test if the array
was non-empty.
The mistake was detected by
http://errorprone.info/bugpattern/SizeGreaterThanOrEqualsZero.

Fix a no-op comparison

---

cglib/src/main/java/net/sf/cglib/proxy/BridgeMethodResolver.java
cglib/src/test/java/net/sf/cglib/proxy/TestEnhancer.java

In both cases we need to avoid using invokesuper. For interface bridges,
using invokesuper will fail since the method being bridged to is in a
superinterface, not a superclass.
Starting in Java 8, javac emits default bridge methods in interfaces,
which use invokeinterface to bridge to the target method.
Without this fix, the included test case fails with:
```
Caused by: java.lang.NoSuchMethodError: java.lang.Object.f(Ljava/lang/Object;)V
at B$$EnhancerByCGLIB$$7aa3e8e0.f(<generated>)
... 28 more
```

Treat invokeinterface bridges similarly to invokespecial

---

cglib/pom.xml
pom.xml

Hi,
The `<optional>true</optional>` attribute of the ant dependency defined in the `dependencyManagement` section of the root pom isn't inherited by the cglib pom. The dependency isn't optional as expected. Here is a patch fixing this.

The Ant dependency isn't optional as expected

---

cglib/src/main/java/net/sf/cglib/core/CodeEmitter.java

Even though they are methods on an interface type, invokeinterface is only for instance method. This code was added >15 years ago, long before static methods were allowed on interfaces.

Use invokestatic on static interface methods

---

cglib/src/main/java/net/sf/cglib/beans/BeanCopier.java
cglib/src/main/java/net/sf/cglib/beans/BeanGenerator.java
cglib/src/main/java/net/sf/cglib/beans/BeanMapEmitter.java
cglib/src/main/java/net/sf/cglib/beans/BulkBeanEmitter.java
cglib/src/main/java/net/sf/cglib/beans/ImmutableBean.java
cglib/src/main/java/net/sf/cglib/core/CodeEmitter.java
cglib/src/main/java/net/sf/cglib/core/KeyFactory.java
cglib/src/main/java/net/sf/cglib/proxy/Enhancer.java
cglib/src/main/java/net/sf/cglib/proxy/InterfaceMaker.java
cglib/src/main/java/net/sf/cglib/proxy/MixinEmitter.java
cglib/src/main/java/net/sf/cglib/reflect/ConstructorDelegate.java
cglib/src/main/java/net/sf/cglib/reflect/FastClassEmitter.java
cglib/src/main/java/net/sf/cglib/reflect/MethodDelegate.java
cglib/src/main/java/net/sf/cglib/reflect/MulticastDelegate.java
cglib/src/main/java/net/sf/cglib/util/ParallelSorterEmitter.java
cglib/src/main/java/net/sf/cglib/util/StringSwitcher.java

This is necessary for https://github.com/cglib/cglib/commit/380ef56d63756e0a26cce2f8016b3d949482907d to work properly on all JDKs

Fix invokestatic on interfaces in JDK 9+ and begin emitting Java 8 bytecode in FastClass to support it

---

cglib/src/main/java/net/sf/cglib/reflect/MethodDelegate.java

This fixes a build error when no classes in `net.sf.cglib` are on the
classpath.

Remove an unused wildcard import
